// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMw60ajKoCGS8Fsf1rfSU9-aSxTvF0cMg',
    appId: '1:587390246813:web:132a4c337b787ea3fb5974',
    messagingSenderId: '587390246813',
    projectId: 'percentage-calculator-d9d39',
    authDomain: 'percentage-calculator-d9d39.firebaseapp.com',
    databaseURL: 'https://percentage-calculator-d9d39.firebaseio.com',
    storageBucket: 'percentage-calculator-d9d39.appspot.com',
    measurementId: 'G-BM18BPXY7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd2ljhOH7SPIlyUr_i17STJlX2FptGLO4',
    appId: '1:587390246813:android:a71910fe8374d53dfb5974',
    messagingSenderId: '587390246813',
    projectId: 'percentage-calculator-d9d39',
    databaseURL: 'https://percentage-calculator-d9d39.firebaseio.com',
    storageBucket: 'percentage-calculator-d9d39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcLrrt0aWER33HDL8q1uXbKx36A5hp-2g',
    appId: '1:587390246813:ios:01bc91a78451039efb5974',
    messagingSenderId: '587390246813',
    projectId: 'percentage-calculator-d9d39',
    databaseURL: 'https://percentage-calculator-d9d39.firebaseio.com',
    storageBucket: 'percentage-calculator-d9d39.appspot.com',
    iosClientId: '587390246813-a8qr58pfcf25ubl4lfpd6b99olrtjt06.apps.googleusercontent.com',
    iosBundleId: 'com.techoveride.percentageCalculator',
  );
}
